insert into dish (nam, slug) values 
('Banh bao', 'banh-bao'),
('Banh beo', 'banh-beo'),
('Banh bot loc', 'banh-bot-loc'),
('Banh can', 'banh-can'),
('Banh canh', 'banh-canh'),
('Banh chung', 'banh-chung'),
('Banh cuon', 'banh-cuon'),
('Banh duc', 'banh-duc'),
('Banh gio', 'banh-gio'),
('Banh hoi', 'banh-hoi'),
('Banh khot', 'banh-khot'),
('Banh mi', 'banh-mi'),
('Banh pia', 'banh-pia'),
('Banh tet', 'banh-tet'),
('Banh tranh nuong', 'banh-tranh-nuong'),
('Banh xeo', 'banh-xeo'),
('Bun bo hue', 'bun-bo-hue'),
('Bun cha ca', 'bun-cha-ca'),
('Bun dau mam tom', 'bun-dau-mam-tom'),
('Bun man', 'bun-man'),
('Bun rieu', 'bun-rieu'),
('Bun thit nuong', 'bun-thit-nuong'),
('Ca kho to', 'ca-kho-to'),
('Canh chua', 'canh-chua'),
('Canh kho qua', 'canh-kho-qua'),
('Cao lau', 'cao-lau'),
('Cha gio', 'cha-gio'),
('Chao long', 'chao-long'),
('Chuoi', 'chuoi'),
('Com cuon', 'com-cuon'),
('Com tam', 'com-tam'),
('Com trang', 'com-trang'),
('Goi cuon', 'goi-cuon'),
('Hu tieu', 'hu-tieu'),
('Mam chung', 'mam-chung'),
('Mi quang', 'mi-quang'),
('Muc xao chua ngot', 'muc-xao-chua ngot'),
('Nem chua', 'nem-chua'),
('Ngheu hap sa', 'ngheu-hap-sa'),
('Pho', 'pho'),
('Tom rim', 'tom-rim'),
('Xoi xeo', 'xoi-xeo');
